# Generated by Django 6.0 on 2025-12-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SP2DK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=200)),
                ('sp2dk', models.IntegerField()),
                ('lhp2dk', models.IntegerField()),
                ('outstanding', models.IntegerField()),
                ('potensi', models.DecimalField(decimal_places=2, max_digits=20)),
                ('realisasi', models.DecimalField(decimal_places=2, max_digits=20)),
                ('kesimpulan_lhp2dk', models.CharField(max_length=200)),
                ('tahun', models.IntegerField()),
                ('bulan', models.IntegerField()),
            ],
        ),
    ]
