# Generated by Django 6.0 on 2025-12-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sp2dk',
            name='bulan',
        ),
        migrations.RemoveField(
            model_name='sp2dk',
            name='kesimpulan_lhp2dk',
        ),
        migrations.RemoveField(
            model_name='sp2dk',
            name='lhp2dk',
        ),
        migrations.RemoveField(
            model_name='sp2dk',
            name='outstanding',
        ),
        migrations.RemoveField(
            model_name='sp2dk',
            name='sp2dk',
        ),
        migrations.RemoveField(
            model_name='sp2dk',
            name='unit',
        ),
        migrations.AddField(
            model_name='sp2dk',
            name='kesimpulan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sp2dk',
            name='lhp2dk_nomor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sp2dk',
            name='lhp2dk_tanggal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sp2dk',
            name='nama_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sp2dk',
            name='nama_wp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sp2dk',
            name='sp2dk_nomor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sp2dk',
            name='sp2dk_tanggal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sp2dk',
            name='potensi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='sp2dk',
            name='realisasi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='sp2dk',
            name='tahun',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
