# Generated by Django 6.0 on 2025-12-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_sp2dk_bulan_remove_sp2dk_kesimpulan_lhp2dk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sp2dk',
            old_name='potensi',
            new_name='estimasi_lha_mandiri',
        ),
        migrations.RenameField(
            model_name='sp2dk',
            old_name='tahun',
            new_name='jumlah_dalam_pengawasan',
        ),
        migrations.RenameField(
            model_name='sp2dk',
            old_name='kesimpulan',
            new_name='petugas_pengawasan',
        ),
        migrations.RenameField(
            model_name='sp2dk',
            old_name='lhp2dk_nomor',
            new_name='unit_kerja',
        ),
        migrations.RemoveField(
            model_name='sp2dk',
            name='lhp2dk_tanggal',
        ),
        migrations.RemoveField(
            model_name='sp2dk',
            name='nama_ar',
        ),
        migrations.RemoveField(
            model_name='sp2dk',
            name='sp2dk_nomor',
        ),
        migrations.RemoveField(
            model_name='sp2dk',
            name='sp2dk_tanggal',
        ),
        migrations.AddField(
            model_name='sp2dk',
            name='estimasi_pemicu_data_lain',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='sp2dk',
            name='jumlah_lhp2dk_selesai',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sp2dk',
            name='jumlah_sp2dk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sp2dk',
            name='jumlah_usul_bukper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sp2dk',
            name='jumlah_usul_pemeriksaan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sp2dk',
            name='nilai_dalam_pengawasan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='sp2dk',
            name='nilai_data_pemicu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='sp2dk',
            name='nilai_potensi_akhir_lhp2dk_selesai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='sp2dk',
            name='nilai_potensi_analisis_mandiri',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='sp2dk',
            name='nilai_potensi_awal_sp2dk',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='sp2dk',
            name='nilai_potensi_lha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='sp2dk',
            name='nilai_usul_bukper',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='sp2dk',
            name='nilai_usul_pemeriksaan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='sp2dk',
            name='no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sp2dk',
            name='npwp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sp2dk',
            name='tahun_pajak',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sp2dk',
            name='total_estimasi_dpp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
