# Generated by Django 6.0 on 2025-12-31 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_potensi_sp2dk_estimasi_lha_mandiri_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sp2dk',
            old_name='estimasi_pemicu_data_lain',
            new_name='estimasi_data_lain',
        ),
        migrations.RenameField(
            model_name='sp2dk',
            old_name='nilai_potensi_akhir_lhp2dk_selesai',
            new_name='nilai_lhp2dk_selesai',
        ),
    ]
