# Generated by Django 6.0 on 2026-01-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_estimasi_pemicu_data_lain_sp2dk_estimasi_data_lain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SP2DKClosed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip_ar', models.CharField(blank=True, max_length=50, null=True)),
                ('nama_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('npwp', models.CharField(blank=True, max_length=50, null=True)),
                ('nama_wp', models.CharField(blank=True, max_length=255, null=True)),
                ('nomor_lhp2dk', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_lhp2dk', models.DateField(blank=True, null=True)),
                ('nomor_sp2dk', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_sp2dk', models.DateField(blank=True, null=True)),
                ('tahun_sp2dk', models.IntegerField(blank=True, null=True)),
                ('estimasi_potensi_sp2dk', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('kesimpulan', models.CharField(blank=True, max_length=50, null=True)),
                ('estimasi_potensi_lhp2dk', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('realisasi', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('nomor_dspp', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_dspp', models.DateField(blank=True, null=True)),
                ('nomor_np2', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_np2', models.DateField(blank=True, null=True)),
                ('nomor_sp2', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_sp2', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
