# Generated by Django 6.0 on 2026-01-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_sp2dkclosed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, null=True)),
                ('npwp', models.CharField(blank=True, max_length=50, null=True)),
                ('nama_wp', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_kerja', models.CharField(blank=True, max_length=255, null=True)),
                ('petugas_pengawasan', models.CharField(blank=True, max_length=255, null=True)),
                ('tahun_pajak', models.IntegerField(blank=True, null=True)),
                ('nilai_potensi_lha', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('nilai_data_pemicu', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('nilai_potensi_analisis_mandiri', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('estimasi_lha_mandiri', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('estimasi_data_lain', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_estimasi_dpp', models.DecimalField(decimal_places=2, max_digits=20)),
                ('jumlah_sp2dk', models.IntegerField(default=0)),
                ('nilai_potensi_awal_sp2dk', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('jumlah_lhp2dk_selesai', models.IntegerField(default=0)),
                ('nilai_lhp2dk_selesai', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('jumlah_usul_pemeriksaan', models.IntegerField(default=0)),
                ('nilai_usul_pemeriksaan', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('jumlah_usul_bukper', models.IntegerField(default=0)),
                ('nilai_usul_bukper', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('jumlah_dalam_pengawasan', models.IntegerField(default=0)),
                ('nilai_dalam_pengawasan', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('realisasi', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='SP2DKCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npwp', models.CharField(max_length=50)),
                ('nama_wp', models.CharField(max_length=255)),
                ('nip_ar', models.CharField(max_length=50)),
                ('nama_ar', models.CharField(max_length=255)),
                ('lhpt_nomor', models.CharField(blank=True, max_length=100, null=True)),
                ('lhpt_tanggal', models.DateField(blank=True, null=True)),
                ('nomor_sp2dk', models.CharField(max_length=100)),
                ('tanggal_sp2dk', models.DateField()),
                ('tahun_pajak', models.IntegerField()),
                ('estimasi_potensi_sp2dk', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('nomor_lhp2dk', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_lhp2dk', models.DateField(blank=True, null=True)),
                ('keputusan', models.CharField(blank=True, max_length=100, null=True)),
                ('kesimpulan', models.CharField(blank=True, max_length=50, null=True)),
                ('estimasi_potensi_lhp2dk', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('realisasi', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('dspp_nomor', models.CharField(blank=True, max_length=100, null=True)),
                ('dspp_tanggal', models.DateField(blank=True, null=True)),
                ('np2_nomor', models.CharField(blank=True, max_length=100, null=True)),
                ('np2_tanggal', models.DateField(blank=True, null=True)),
                ('sp2_nomor', models.CharField(blank=True, max_length=100, null=True)),
                ('sp2_tanggal', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SP2DKPrevious',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npwp', models.CharField(max_length=50)),
                ('nama_wp', models.CharField(max_length=255)),
                ('nip_ar', models.CharField(max_length=50)),
                ('nama_ar', models.CharField(max_length=255)),
                ('lhpt_nomor', models.CharField(blank=True, max_length=100, null=True)),
                ('lhpt_tanggal', models.DateField(blank=True, null=True)),
                ('nomor_sp2dk', models.CharField(max_length=100)),
                ('tanggal_sp2dk', models.DateField()),
                ('tahun_pajak', models.IntegerField()),
                ('estimasi_potensi_sp2dk', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('nomor_lhp2dk', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_lhp2dk', models.DateField(blank=True, null=True)),
                ('keputusan', models.CharField(blank=True, max_length=100, null=True)),
                ('kesimpulan', models.CharField(blank=True, max_length=50, null=True)),
                ('estimasi_potensi_lhp2dk', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('realisasi', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('dspp_nomor', models.CharField(blank=True, max_length=100, null=True)),
                ('dspp_tanggal', models.DateField(blank=True, null=True)),
                ('np2_nomor', models.CharField(blank=True, max_length=100, null=True)),
                ('np2_tanggal', models.DateField(blank=True, null=True)),
                ('sp2_nomor', models.CharField(blank=True, max_length=100, null=True)),
                ('sp2_tanggal', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SP2DK',
        ),
        migrations.DeleteModel(
            name='SP2DKClosed',
        ),
    ]
