# Generated by Django 6.0 on 2026-01-10 06:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_dpp_sp2dkcurrent_sp2dkprevious_delete_sp2dk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpp',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
