# Generated by Django 6.0 on 2026-01-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_dpp_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sp2dkcurrent',
            name='tanggal_sp2dk',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sp2dkprevious',
            name='tanggal_sp2dk',
            field=models.DateField(blank=True, null=True),
        ),
    ]
