# Generated by Django 6.0 on 2026-01-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_sp2dkcurrent_tanggal_sp2dk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sp2dkcurrent',
            name='nomor_sp2dk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sp2dkcurrent',
            name='tahun_pajak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sp2dkprevious',
            name='nomor_sp2dk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sp2dkprevious',
            name='tahun_pajak',
            field=models.IntegerField(default=0),
        ),
    ]
