# Generated by Django 6.0 on 2026-01-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_sp2dkcurrent_nomor_sp2dk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sp2dkcurrent',
            name='tahun_pajak',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sp2dkprevious',
            name='tahun_pajak',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
